### ISSUE TITLE
y2s function is wrong

### ISSUE THREAD

**Issue by eskiyerli** [dsmi/embox#1]
### Y2S function is incorrectly coded
I spent quite a bit time trying to make sense of s-parameters generated by y2s function. Finally I tracked it down to incorrect y2s function. I think you picked it up from a toolbox published in matlab repositories. I just coded a simple 2-port y2s function that works correctly.

function s = y2s(y,varargin)
% S = y2s(Y,Z0)
%
% Admittance to Scattering transformation
% for square matrices at multiple frequencies
% 
% Murat Eskiyerli, 2020.
if nargin == 2
  Z0=varargin{1};
elseif nargin == 1
  Z0=50;
else
  error("wrong number of arguments");
endif
detZ=(1+Z0*y(1,1))*(1+Z0*y(2,2))-Z0**2*y(1,2)*y(2,1);
s(1,1)=((1-Z0*y(1,1))*(1+Z0*y(2,2))+Z0**2*y(1,2)*y(2,1))/detZ;
s(1,2)=-2*Z0*y(1,2)/detZ;
s(2,1)=-2*Z0*y(2,1)/detZ;
s(2,2)=((1+Z0*y(1,1))*(1-Z0*y(2,2))+Z0**2*y(1,2)*y(2,1))/detZ;
endfunction

**Comment by dsmi** [comment]
Hi Murat,
You are right regarding the source of this function.
Also, I am pretty sure that it works correctly, but -- it returns 1Ohm normalized S-parameters; which, I agree, might be confusing. You can use renorms function, included with embox, to re-normalize to 50Ohm or any other value.
Thanks again for your interest in my solvers, and let me know if you need help with anything!
